### ISSUE TITLE
4K background image is cropped if scaling enabled

### ISSUE THREAD

**Issue by Nexion** [gergo-salyi/multibg-sway#4]
My laptop display is eDP-1 1920x1080, no scaling. The external HDMI display is 3840@2160, scale 2.

If I put a 4K wallpaper picture for the HDMI display in WALLPAPER_DIR, only the center part (1920x1080) of the picture is on the display. The behavior of `swaybg` is expected in this case, it renders the whole picture. Could you please make `multibg-sway` work the same way?

**Comment by gergo-salyi** [comment]
Thank you for the report!

I could reproduce this with `$ swaymsg output HDMI-A-1 scale 2`. That is the kind of way have too right?

I wouldn't say I 100% understand how integer scale factors are handled in our wayland client library, but I think I managed to add the code that was needed to fix this - only for whole integer scale factors for now.

I released 0.1.5 to crates.io and AUR. 
Please test it, and tell me here if it worked. Thanks!

**Comment by Nexion** [comment]
That was unbelievably fast :) Works like a charm, thanks a lot.

**Comment by gergo-salyi** [comment]
OK. You're welcome!
